# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Open GitHub pull request"
  lane :pr do
    # Read framework version
    plist_file = "../Appier.xcframework/ios-arm64_armv7/Appier.framework/Info.plist"
    framework_version = sh("/usr/libexec/PlistBuddy #{plist_file} -c 'Print :CFBundleShortVersionString'").strip

    # Set Podspec version
    version_file = {
      "version" => framework_version
    }

    File.write("../version.json", version_file.to_json)

    # Commit and push changes
    git_commit(
      path: [
        "./*.xcframework/*",
        "./version.json"
      ],
      message: "Release #{framework_version}"
    )

    push_to_git_remote(
      force: true
    )

    # Open pull request
    github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "POST",
      path: "/repos/nckh/appier-ios-framework/pulls",
      # path: "/repos/appier/appier-ios-framework/pulls",
      body: {
        # "head": "release",
        "head": "ci/fastlane",
        "base": "master",
        "title": "Release v#{framework_version}"
      }
    )
  end

  desc "Deploy Podspecs to CocoaPods Trunk"
  lane :deploy do



  end

end
