# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Open GitHub PR"
  lane :open_github_pr do
    plist_file = "../Appier.xcframework/ios-arm64_armv7/Appier.framework/Info.plist"
    framework_version = sh("/usr/libexec/PlistBuddy #{plist_file} -c 'Print :CFBundleShortVersionString'").strip

    version_file = {
      "version" => framework_version
    }

    File.write("../version.json", version_file.to_json)

    git_commit(
      path: [
        "./*.xcframework/*",
        "./version.json"
      ],
      message: "Release #{framework_version}"
    )

    # TODO: PR
  end

  desc "Deploy Podspecs to CocoaPods Trunk"
  lane :deploy_podspecs do
  end

end
